src/components/card/CardForm.tsx
- 자유 형식 폼에 삭제 기능을 추가하였습니다.
- 아직 main에 자유형식 폼 ui가 머지되지 않아 css 작업을 하지 않고 단순한 삭제 버튼 ui와 삭제 기능만 추가하였습니다.
=> feat: 자유 형식 항목 삭제 기능 추가

src/components/card/CardForm.tsx
- 머지할 때 누락된 비밀번호 필드, sns 필드 ui를 추가하였습니다.
=> fix: 비밀번호 필드, sns 필드 ui 추가

src/pages/[id]/edit/index.tsx, src/pages/[id]/index.tsx, src/pages/[id]/login/index.tsx, src/pages/default/edit/index.tsx
이전 커밋으로 인해서 잘못 지운 파일을 복구하였습니다.
=> fix: 잘못 지운 파일복구

src/pages/api/twitter-info/[twitterId]/index.ts
트위터 크롤링 API에서 유저 닉네임 필드 추가하였습니다.
=> feat: 트위터 크롤링 API에서 유저 닉네임 필드 추가

src/pages/api/twitter-info/[twitterId]/index.ts
이슈 #38
트위터 크롤링 이미지 업데이트 API 를 추가하고 이미지 불러오기 API 로 나누었습니다.
=> feat: 트위터 크롤링 이미지 업데이트 API 추가하기

src/pages/api/twitter-info/[twitterId]/index.ts, src/utils/switchCrawler.ts
트위터 크롤링 API 에서 응답이 없을경우, 인스턴스 URL 을 전환하여 요청하도록 변경하였습니다.
=> feat: 크롤러 인스턴스 전환하게 변경

src/pages/api/cards/[cardId].ts, src/pages/api/twitter-info/[twitterId]/index.ts
한번에 업데이트 할 수 있게 카드 업데이트 API PUT 메서드에 트위터 크롤링 저장 API 합쳤습니다.
=> feat: 카드 업데이트 API PUT 메서드에 트위터 크롤링 저장 API 합치기

package.json, src/components/card/CardForm.tsx, src/components/card/NameCard.tsx, yarn.lock
관련이슈: #24
명함 컴포넌트를 분리하였습니다.
자유형식 빼기 버튼 아이콘을 변경하였습니다.
=> feat: 명함 컴포넌트 분리

src/components/modal/BottomSheet.tsx, src/components/modal/QRModal.tsx, src/hooks/queries/useCreateShortLink.ts
- QR코드 모달이 보여질 때 cardId로 숏링크 아이디를 받아오고, 이를 포함한 URL로 QR코드를 만들도록 하였습니다.
- 숏링크 아이디를 받아오는 부분에서 response가 정상적으로 오지만 프론트에서는 undefined로 가져오는 오류를 해결하였습니다.
=> feat: QR코드에 숏링크 URL 연결하기

database.types.ts, package.json, src/utils/supabase.js, src/utils/supabase.ts, yarn.lock
=> feat: Supabase 타입 젠

.husky/commit-msg, .husky/pre-commit, .vscode/settings.json, database.types.ts, package.json, src/components/card/CardForm.tsx, src/pages/[id]/edit/index.tsx, src/pages/[id]/index.tsx, src/pages/api/cards/[cardId].ts, src/pages/api/cards/[cardId]/login.ts, src/pages/api/cards/[cardId]/thumbnail.tsx, src/pages/api/cards/index.ts, src/pages/api/twitter-info/[twitterId]/index.ts, src/pages/default/edit/index.tsx, src/pages/default/index.tsx, src/utils/prisma.ts, yarn.lock
=> fix: fix build

src/components/SEO/SEO.tsx, src/components/modal/BottomSheet.tsx, src/components/modal/QRModal.tsx, src/pages/card/[cardId]/index.tsx
- 모든 공유하기 url을 숏링크로 수정하였습니다.(트윗 공유하기, 링크 복사하기, QR코드에 삽입된 url)
- 배포된 링크 공유시 썸네일 이미지가 보이지 않는 오류를 해결하였습니다(경로 수정)
=> feat: 모든 공유하기 url을 숏링크로 수정

src/pages/api/cards/[cardId].ts, src/pages/api/cards/index.ts
명함정보를 가져올 때 cardId로 잘못 전해지는 image_url 값을 변경하였습니다.
=> fix: 명함 정보를 가져올 때 잘못된 image_url 값 변경

src/components/SEO/SEO.tsx, src/components/card/CardItem.tsx, src/components/ui/BottomNavigation.tsx, src/pages/card/[cardId]/index.tsx
- 명함 상세 페이지의 meta tag description을 수정하였습니다.
- meta image 경로를 수정하였습니다.
- 메인 페이지에서 명함 아이템의 명함에 보더를 추가하여 스타일링하였습니다.
=> feat: 명함 아이템 스타일링 및 메뉴바 비활성화 오류 해결

src/utils/errorHandler.ts
=> feat: 에러 핸들러 에러 출력수정

src/components/SEO/SEO.tsx
=> feat: twitter meta tag 수정

next.config.js, src/pages/api/short-link/[shortLink]/index.ts, src/utils/errorHandler.ts
=> feat: 숏링크 리다이렉트

src/components/modal/BottomSheet.tsx, src/components/modal/QRModal.tsx
=> fix: 숏링크 경로에 s 추가

src/components/SEO/SEO.tsx
=> feat: 구글 애널리틱스 연결

src/components/card/CardItem.tsx, src/pages/api/twitter-info/[twitterId]/index.ts
=> feat: card padding 변경

src/pages/api/twitter-info/[twitterId]/index.ts, src/utils/showToastMessage.ts
- toast 에러 메시지로 서버에서 가져온 메시지를 프론트에 보여주지 않고 '서버 에러가 발생했습니다.'라는 문구만 일괄적으로 보여지게끔 수정하였습니다.
=> feat: 에러 메시지 수정

src/pages/api/twitter-info/[twitterId]/index.ts, src/utils/showToastMessage.ts
- 비밀번호 불일치시 서버에서 가져온 오류 메시지를 클라이언트에 표시하도록 수정하였습니다.
=> feat: 비밀번호 불일치 오류 메시지 추가

src/components/modal/BottomSheet.tsx, src/pages/api/twitter-info/[twitterId]/index.ts
=> feat: 트위터 공유 메시지 수정

src/components/modal/BottomSheet.tsx
=> feat: 트위터 공유시 해시태그 추가

src/components/card/CardItem.tsx, src/pages/card/[cardId]/index.tsx
- cursor-pointer 속성을 추가했습니다.
-  명함 아이템을 div 태그를 Link로 수정하였습니다.
=> feat: cursor-pointer 추가 및 link 태그로 변경

src/components/card/CardForm.tsx
- 자유형식 폼 검증 로직을 추가하였습니다.
- 빈 값이 서버에 올라가지 않도록 수정하였습니다.
=> fix: 폼 검증 로직 추가

src/hooks/queries/useGetCards.ts, src/pages/api/cards/index.ts, src/pages/index.tsx
Reverts ramgee-zzik-nabi/application#107
=> Revert "카드 검색 기능 추가"

src/components/layout/HomeLayout.tsx, src/pages/index.tsx
- 커피한잔 문장 더 짧게 수정
- 검색창 안에 input이 모바일에서 회색으로 표시되는 오류 해결
=> fix: 검색창, 커피한잔 스타일 수정

src/components/card/CardForm.tsx, src/pages/card/[cardId]/index.tsx
- 아이디 앞에 @를 붙여서 사용자가 @를 따로 붙이지 않도록 했습니다.
- url 앞에 https://를 붙여서 사용자가 https://를 url 필드에 쓰지 않도록 했습니다.
- 사용자가 적은 url을 Link로 타고 들어갈 때 자동으로 https://를 붙여줘서 정상적인 링크로 이동할 수 있도록 했습니다.
- 기존 명함 데이터의 url에서 https://를 모두 빼주셔야 할 것 같습니다..! 그런데 그러면 명함 이미지도 https://가 없는 거로 바뀌나요?
=> feat: 아이디 input 앞에 @ 추가, url 앞에 https:// 글자 추가

src/components/card/CardItem.tsx
new를 포함한 명함 설명 ui(메인 페이지에서)를 수정했습니다.
=> feat: new를 포함한 명함 설명 ui 수정

package.json, src/hooks/queries/useGetCards.ts, src/pages/api/cards/index.ts, src/pages/index.tsx, yarn.lock
=> feat: 무한 스크롤 구현

src/components/card/CardItem.tsx, src/pages/_app.tsx
- 업데이트 날짜 글자 색상을 바꿔서 접근성을 향상했습니다.
- google analytics script를 미리 불러오도록 변경했습니다.
=> refactor: 성능 및 접근성 개선
